### ISSUE TITLE
Question - Is it compatible with GraphQL api?

### ISSUE THREAD

**Issue by dredscabral** [mkharibalaji/react-native-adyen-payment#81]
I was reading the documentation and saw in the example that we pass a baseUrl param. I wonder if this is something set on the Adyen Dashboard or if this is for our own API. If it's with our own API would it work with a GraphQL api and how if we don't have paths just queries?  

Thank you!

**Comment by ChielBruin** [comment]
this `baseUrl` refers to your own server, which in turn communicates to the Adyen servers (also see a similar answer here: [#76](https://github.com/mkharibalaji/react-native-adyen-payment/issues/76#issuecomment-1075541965)). I have no experience with GraphQL, so I cannot help you there. There might be some information about integrating Adyen drop-ins with a GraphQL backend on the web, otherwise you could always contact Adyen support directly.

**Comment by dredscabral** [comment]
Thank you for answering my question, @ChielBruin!
